In [5]:
import numpy as np

In [15]:
np.random.rand(5)     # newer values on every implementation

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [16]:
np.random.seed(42)  # setting same seed we will give same random numbers.

In [17]:
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [18]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [19]:
np.random.seed(42)  # proving that we will get same random numbers

In [20]:
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [21]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [22]:
np.random.seed(82)

In [23]:
np.random.rand(5)

array([0.27522567, 0.63923076, 0.62389921, 0.77804231, 0.47811353])

In [24]:
np.random.rand(5)

array([0.95913389, 0.99743421, 0.83251328, 0.20384505, 0.13405   ])

In [25]:
np.random.rand(5)

array([0.61501462, 0.59298706, 0.64478049, 0.98872053, 0.33516261])

In [26]:
np.random.seed(82)  # again proving

In [27]:
np.random.rand(5)

array([0.27522567, 0.63923076, 0.62389921, 0.77804231, 0.47811353])

In [28]:
np.random.rand(5)

array([0.95913389, 0.99743421, 0.83251328, 0.20384505, 0.13405   ])

In [29]:
np.random.rand(5)

array([0.61501462, 0.59298706, 0.64478049, 0.98872053, 0.33516261])